@ #58 | should install require modules when ansible was installed
teracyhq-incubator/teracy-dev-k8s pull request #59
Opened 2018-12-05 11:42 UTC by hieptranquoc

connect #58 
resolved: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s/issues/14
please check this PR! Thank you!

2018-12-05 12:00 UTC, hoatle requested changes
@hieptranquoc pls check my comments

2018-12-05 12:00 UTC, hoatle commented on provisioners/ansible/.gitignore
> +k8s-requirements.retry
*.retry

2018-12-05 12:00 UTC, hoatle commented on provisioners/ansible/k8s-requirements.yml
> +      register: pip_check
pip_exist

2018-12-05 12:00 UTC, hoatle commented on provisioners/ansible/k8s-requirements.yml
> +    - name: check pip exists
- name: Check pip exists

2018-12-05 12:00 UTC, hoatle commented on provisioners/ansible/k8s-requirements.yml
> +    - debug:
should send warning

2018-12-05 12:00 UTC, hoatle commented on provisioners/ansible/k8s-requirements.yml
> +    - name: install teracy-dev-k8s requirements
Install Kuberspray pip requirements

2018-12-05 12:00 UTC, hoatle commented on lib/teracy-dev-k8s/processors/settings.rb
> +                "_id" => "requirement-0",
"_id" => "k8s-pip-requirements"

2018-12-06 09:26 UTC, hieptranquoc commented
I've updated! Please check this PR again! Thank you!

2018-12-06 09:49 UTC, hoatle approved these changes
LGTM

2018-12-06 09:49 UTC, merged