@ #28 | add docs how to install kubectl helm
teracyhq-incubator/teracy-dev-k8s pull request #78
Opened 2019-01-25 11:10 UTC by hieptranquoc

connect #28 
please check this PR! Thank you.

2019-01-30 09:51 UTC, hoavt reviewed
@hieptranquoc please check my comments

2019-01-30 09:51 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +	+ Install latest version with `kubectl` binary using `curl`(please install `curl` if you don't have it).
we don;t need to mention the installation with curl. Just installation with brew is enough.

2019-01-30 09:51 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +	+ If you have ever installed the desired version with `homebrew`, you can downgrade to that version.
you can switch to that version.

(we use the "switch" word, because we can switch from an old version to the newer version)

2019-01-30 09:51 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +This page shows you how to install kubectl and helm on macOS, Linux (Ubuntu) and Windows
Assume:
Assume:
homebrew available on macOS
chocolatey available on Windows
Ubuntu is preferred Linux distro

@hieptranquoc so we should show this, moreover, teracy-dev users have had them.

- I don;t see the section how to upgrade the version.

2019-01-30 09:51 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +> If bash-completion in Homebrew not work, please add to `~/.bash_profile`:
does not work

2019-01-31 03:13 UTC, hieptranquoc commented
Reply to all @hoavt comments: we can't switch version if we haven't installed it yet. So we need `curl` to install any version, include ( downgrade, upgrade ).

2019-02-20 06:46 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +	+ If you have ever installed the desired version with `homebrew`, you can downgrade to that version.
@hieptranquoc I mean, we should use the word "switch", not "downgrade".

2019-02-20 06:59 UTC, hoavt reviewed
https://github.com/hieptranquoc/teracy-dev-k8s/commit/cae56c924f7d26ec516b23097e0e0d063822c0ee#diff-5bda4a488e3bf7ddca37c694c0c16c92L115

why don;t show how to upgrade a newer version @hieptranquoc?

2019-02-20 06:59 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +- Latest version:
If we mention 2 ways to install, the structure should be 
- Install Kubectl with brew
- Install Kubectl with curl

And remove the unnecessary lines.

2019-02-20 06:59 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +	For example, to download version v1.12.0 on macOS, type:
In my previous doc, I also mentioned how to install a specific version with brew. https://www.benpickles.com/articles/72-downgrading-kubectl-with-homebrew

2019-05-06 09:15 UTC, hieptranquoc commented
I've updated! Please check this PR again!

2019-05-08 00:42 UTC, hoavt reviewed
Please check my changes @hieptranquoc.

2019-05-08 00:42 UTC, hoavt commented on docs/how-to-install-kubectl-helm.md
> +This page shows you how to install kubectl and helm on macOS, Linux (Ubuntu) and Windows
Should have a Stop punctuation at the end of the sentence.

2019-05-09 08:56 UTC, hieptranquoc commented
@hoavt I've updated! Please check this PR again!

2019-05-10 07:29 UTC, hieptranquoc commented
@hoatle Please check! All done!

2019-05-10 07:40 UTC, hoatle commented
need @hoavt to approve this.

2019-05-13 12:36 UTC, hoavt submitted a review, later dismissed

2019-05-14 02:40 UTC, hoatle requested changes
@hieptranquoc please check my comments.

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +- At least ubuntu 16.04
Ubuntu

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +	+ [Installing / Uninstalling kubeclt on macOS](#kubectl_mac_os)
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +	+ [Installing / Uninstalling kubeclt on Linux(Ubuntu)](#kubectl_linux)
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +	+ [Installing / Uninstalling kubeclt on Windows](#kubectl_windows)
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +- Test `kubectl` version you installed:
`helm`

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +	$ kubectl version
helm

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +## <a name="kubectl_mac_os"></a>Installing / Uninstalling kubeclt on macOS
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +### Installing kubeclt on macOS
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +- Install kubeclt with `homebrew`:
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +- Downgrade kubeclt with `homebrew`: See the details at https://www.benpickles.com/articles/72-downgrading-kubectl-with-homebrew to downgrade with `homebrew`.
`kubectl`

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +- Install a kubeclt specific version with `curl`:
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +### Uninstalling kubeclt on macOS
kubectl

2019-05-14 02:40 UTC, hoatle commented on docs/how-to-install-kubectl-helm.md
> +# <a name="helm">Helm[Helm]
Helm[Helm] => Helm

2019-05-14 02:59 UTC, hoavt approved these changes
Applied comments @hoatle

2019-05-14 03:01 UTC, hoatle approved these changes
LGTM

2019-05-14 03:01 UTC, merged